name: Build And Test and Deploy to my coolify project
# deploy to coolify.mingull.nl

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Node.js version
              uses: actions/setup-node@v4.0.2
              with:
                  node-version: "20.x"

            - name: npm install and build
              run: |
                  npm install
                  npm run build

            - name: Zip artifact for deployment
              run: zip release.zip ./* -r

            - name: Upload artifact for deployment job
              uses: actions/upload-artifact@v4.3.3
              with:
                  name: node-app
                  path: release.zip

    integrationTests:
        runs-on: ubuntu-latest
        needs: build
        env:
            MYSQL_ROOT_PASSWORD: root # default root password to use must be 'root'
            DB_HOST: 127.0.0.1
            DB_PORT: 3306
            DB_DATABASE: share_a_meal
            DB_USER: root
            DB_PASSWORD: root
        services:
            mysql:
                image: mariadb:11
                ports:
                    - 3306
        steps:
            - name: Download artifact from build job
              uses: actions/download-artifact@v4
              with:
                  name: node-app

            - name: Unzip artifact for tests
              run: unzip release.zip

            - name: Start MySQL connection from host
              run: |
                  sudo /etc/init.d/mysql start
                  sudo apt-get install -y mysql-client
                  mysql -h 127.0.0.1 -uroot -p${{ env.MYSQL_ROOT_PASSWORD }} -e "SHOW DATABASES;"
                  mysql -h 127.0.0.1 -uroot -p${{ env.MYSQL_ROOT_PASSWORD }} -e "CREATE DATABASE ${{env.DB_DATABASE}};"

            - name: Import the database
              run: |
                  mysql -uroot -p${{env.MYSQL_ROOT_PASSWORD}} ${{env.DB_DATABASE}} < share-a-meal.sql
                  mysql -uroot -p${{env.MYSQL_ROOT_PASSWORD}} ${{env.DB_DATABASE}} -e "SHOW TABLES;"

            - name: npm test
              # run the as es module
              run: npm test-js
              # -- --DB_PASSWORD $MYSQL_ROOT_PASSWORD --DB_USER root --DB_NAME $DB_DATABASE --DB_PORT $DB_PORT
    # deploy:
    #     runs-on: ubuntu-latest
    #     permissions:
    #         contents: read
    #         packages: write
    #     steps:
    #         - uses: actions/checkout@v3
    #         - name: Login to ghcr.io
    #           uses: docker/login-action@v2
    #           with:
    #               registry: ${{ env.REGISTRY }}
    #               username: ${{ github.actor }}
    #               password: ${{ secrets.TOKEN  }}
    #         - name: Build image and push to registry
    #           uses: docker/build-push-action@v4
    #           with:
    #               context: .
    #               file: Dockerfile
    #               platforms: linux/amd64
    #               push: true
    #               tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
    #         - name: Deploy to Coolify
    #           run: |
    #               curl --request GET '${{ secrets.COOLIFY_WEBHOOK }}' --header 'Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}'
